name: laravel-sass
recipe: laravel
config:
  webroot: public
services:
  appserver:
    run:
      - "cd $LANDO_MOUNT && composer install"
  database:
    portforward: 3307
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  cli:
    type: node
  redis:
    type: redis
    portforward: 6380
proxy:
  appserver:
    - startup.lndo.site
  mailhog:
    - mail.startup.lndo.site
tooling:
  npm:
    service: cli
  npx:
    service: cli
  node:
    service: cli
  yarn:
    service: cli
